# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class SubmitPage(QtWidgets.QWidget):
    def __init__(self):
        super(SubmitPage, self).__init__()

        # self.setStyleSheet("background-color:white;")
        self.setupUi()
        self.show()

    def setupUi(self):
        # MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1026, 600)
        # self = QtWidgets.QWidget(MainWindow)
        # self.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(-6, 0, 261, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/pi/covide-module/MicrosoftTeams-image (34).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(251, -1, 781, 61))
        self.label_2.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"alternate-background-color: rgb(0, 85, 127);\n"
"font: 75 11pt \"Segoe UI\";")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(4, 59, 251, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(254, 59, 251, 41))
        self.label_4.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(170, 170, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(504, 59, 251, 41))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(754, 59, 271, 41))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 35, 20))
        self.label_7.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 170, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(360, 90, 35, 20))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(610, 90, 35, 20))
        self.label_9.setStyleSheet("color: rgb(0, 85, 127);\n"
"background-color: rgb(255, 170, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(870, 90, 35, 20))
        self.label_10.setStyleSheet("color: rgb(0, 85, 127);\n"
"background-color: rgb(255, 170, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")

        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(150, 94, 211, 16))
        self.line.setStyleSheet("color: rgb(255, 170, 0);\n"
"border-color: rgb(255, 170, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self)
        self.line_2.setGeometry(QtCore.QRect(397, 90, 211, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self)
        self.line_3.setGeometry(QtCore.QRect(647, 94, 221, 16))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(354, 99, 671, 441))
        self.label_11.setStyleSheet("color: rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")

        self.label_14 = QtWidgets.QLabel(self)
        self.label_14.setGeometry(QtCore.QRect(404, 140, 231, 21))
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(self)
        self.label_15.setGeometry(QtCore.QRect(30, 180, 261, 351))
        self.label_15.setStyleSheet("background-color: rgb(219, 255, 164);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")

        self.line_4 = QtWidgets.QFrame(self)
        self.line_4.setGeometry(QtCore.QRect(30, 170, 261, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_5 = QtWidgets.QFrame(self)
        self.line_5.setGeometry(QtCore.QRect(30, 510, 261, 41))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_6 = QtWidgets.QFrame(self)
        self.line_6.setGeometry(QtCore.QRect(13, 180, 41, 351))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_7 = QtWidgets.QFrame(self)
        self.line_7.setGeometry(QtCore.QRect(270, 180, 41, 351))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.label_12 = QtWidgets.QLabel(self)
        self.label_12.setGeometry(QtCore.QRect(370, 140, 31, 16))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("/home/pi/covide-module/tick1.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.label_16 = QtWidgets.QLabel(self)
        self.label_16.setGeometry(QtCore.QRect(370, 160, 31, 16))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("/home/pi/covide-module/tick1.jpg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(self)
        self.label_17.setGeometry(QtCore.QRect(404, 160, 281, 20))
        self.label_17.setObjectName("label_17")

        self.label_18 = QtWidgets.QLabel(self)
        self.label_18.setGeometry(QtCore.QRect(370, 180, 31, 16))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("/home/pi/covide-module/tick1.jpg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(self)
        self.label_19.setGeometry(QtCore.QRect(404, 180, 271, 16))
        self.label_19.setObjectName("label_19")

        self.EmployeeID = QtWidgets.QLabel(self)
        self.EmployeeID.setGeometry(QtCore.QRect(50, 240, 221, 21))
        self.EmployeeID.setObjectName("label_20")
        self.EmployeeID.setText('Employee ID : S020932 ')
        self.EmployeeID.setStyleSheet("color : black;font-weight: bold;font-size: 18px")

        self.Temperature = QtWidgets.QLabel(self)
        self.Temperature.setGeometry(QtCore.QRect(50, 300, 221, 21))
        self.Temperature.setObjectName("label_21")
        self.Temperature.setText('Temperature : 97 °F')
        self.Temperature.setStyleSheet("color : black;font-weight: bold;font-size: 18px")

        self.OxygenLevel = QtWidgets.QLabel(self)
        self.OxygenLevel.setGeometry(QtCore.QRect(50, 360, 221, 21))
        self.OxygenLevel.setObjectName("label_22")
        self.OxygenLevel.setText('O2 Saturation : 99 %')
        self.OxygenLevel.setStyleSheet("color : black;font-weight: bold;font-size: 18px")

        self.HeartRate = QtWidgets.QLabel(self)
        self.HeartRate.setGeometry(QtCore.QRect(50, 420, 221, 21))
        self.HeartRate.setObjectName("label_23")
        self.HeartRate.setText('Heart Rate : 78 BPM')
        self.HeartRate.setStyleSheet("color : black;font-weight: bold;font-size: 18px")
        # MainWindow.setCentralWidget(self)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 18))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">                            WELLNESS MODULE 2.0</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">QR Code</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Temperature</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Oxygen Saturation</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Submit</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">1</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00557f;\">2</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "3"))
        self.label_10.setText(_translate("MainWindow", "4"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p><p><br/></p><p><br/></p><p><span style=\" font-size:16pt; font-weight:600; color:#000000;\">Press Button 1 to Complete</span></p><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#202124;\">प</span><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#202124;\">ूरा करने के लिए बटन 1 दबाएं</span></p><p><br/></p><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Press Button 2 to Retake Measurement</span></p><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#ff0000;\">म</span><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#ff0000;\">ाप फिर से लेने के लिए बटन 2 दबाएं</span></p><p><br/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\"> ID Scanned Successfully</span></p></body></html>"))
        message = "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#00aa00;\">ENTER</span></p><p><span style=\" font-size:11pt;\"><br/></span></p><p><span style=\" font-size:9pt; font-weight:600; color:#00aa00;\">Employee ID:</span><span style=\" font-size:10pt; font-weight:600;\"> {}</span></p><p><span style=\" font-size:11pt;\"><br/></span><span style=\" font-size:11pt; font-weight:600; color:#00aa00;\">Temperature:</span><span style=\" font-size:11pt; font-weight:600;\"> {}</span></p><p><span style=\" font-size:11pt;\"><br/></span><span style=\" font-size:11pt; font-weight:600; color:#00aa00;\">O2 Level:</span><span style=\" font-size:11pt; font-weight:600;\"> {}</span></p></body></html>"
        # self.label_15.setText(_translate("MainWindow", message.format(qr_data, temp1, o2)))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55aa00;\">Temperature taken Successfully</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">Oximeter Reading Taken Successfully</span></p></body></html>"))
