# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class WelcomePage(QtWidgets.QWidget):
    def __init__(self):
        super(WelcomePage, self).__init__()

        # self.setStyleSheet("background-color:white;")
        self.setupUi()

        self.show()

    def setupUi(self):
        # MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1024, 600)
        # self = QtWidgets.QWidget(MainWindow)
        # self.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(-6, 0, 261, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/pi/covide-module/MicrosoftTeams-image (34).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(251, -1, 781, 61))
        self.label_2.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"alternate-background-color: rgb(0, 85, 127);\n"
"font: 75 11pt \"Segoe UI\";")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(4, 59, 251, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(254, 59, 251, 41))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 170, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(504, 59, 251, 41))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 170, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(754, 59, 271, 41))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 170, 127);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(110, 90, 35, 20))
        self.label_7.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 170, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(360, 90, 35, 20))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(610, 90, 35, 20))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(870, 90, 35, 20))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")

        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(150, 94, 211, 16))
        self.line.setStyleSheet("color: rgb(255, 170, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self)
        self.line_2.setGeometry(QtCore.QRect(397, 90, 211, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self)
        self.line_3.setGeometry(QtCore.QRect(647, 94, 221, 16))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(4, 99, 1021, 241))
        self.label_11.setStyleSheet("color: rgb(0, 85, 127);\n"
"color: rgb(0, 85, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")

        self.label_13 = QtWidgets.QLabel(self)
        self.label_13.setGeometry(QtCore.QRect(-6, 339, 1031, 241))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")

        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 18))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">                            WELLNESS MODULE 2.0</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">QR Code</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Temperature</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Oxygen Saturation</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Submit</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">1</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "2"))
        self.label_9.setText(_translate("MainWindow", "3"))
        self.label_10.setText(_translate("MainWindow", "4"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#00557f;\">Welcome to Wellness Module 2.0</span></p><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#00557f;\">व</span><span style=\" font-family:\'inherit\'; font-size:24px; font-weight:600; color:#00557f;\">ेलनेस मॉड्यूल 2.0 में आपका स्वागत है</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#000000;\">Press button 1 to get started</span></p><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:16pt; font-weight:600; color:#000000;\">आ</span><span style=\" font-family:\'inherit\'; font-size:16pt; font-weight:600; color:#000000;\">रंभ करने के लिए बटन 1 दबाएं</span></p></body></html>"))